### ISSUE TITLE
Code coverage not displaying for Vue.js project

### ISSUE THREAD

**Issue by nlafranchi** [sdavis3/code-coverage-widgets#40]
We are using your code coverage widget for a number of .Net projects and it works wonderfully. I have not yet been able to display the coverage results for our NPM unit test task. 

Is it possible to display coverage results for NPM tasks?

I have the code coverage displaying on build summary tab in devOps:
<img width="1398" alt="Screen Shot 2021-03-12 at 10 29 32 AM" src="https://user-images.githubusercontent.com/12193243/110984852-88aa8200-8320-11eb-9e31-25be4139b3a1.png">

But I do not know how to get it to display in the widget: 
<img width="504" alt="Screen Shot 2021-03-12 at 10 28 59 AM" src="https://user-images.githubusercontent.com/12193243/110984941-a4ae2380-8320-11eb-80e8-223a48acb3ae.png">

Any help with this would be greatly appreciated.

Thanks!

**Comment by sdavis3** [comment]
The widget reads the results as they are published by the Azure DevOps API. Are your test results visible in the Summary tab (as shown below)?

<img width="1616" alt="Screen Shot 2021-03-15 at 10 41 33 AM" src="https://user-images.githubusercontent.com/1821509/111171488-5b0d4500-857b-11eb-992c-c1dec4af71d9.png">

**Comment by nlafranchi** [comment]
Yes. They are. Still same results in the dashboard unfortunately.
<img width="1477" alt="Screen Shot 2021-03-16 at 9 13 21 AM" src="https://user-images.githubusercontent.com/12193243/111342735-f8c64a00-8637-11eb-9bd7-0594a8cfa0d1.png">

**Comment by nlafranchi** [comment]
I figured it out. Added the test results and then realized I hadn't chosen the build definition correctly. Thanks for your time and your widget!
