### ISSUE TITLE
Code coverage no longer showing since Wednesday 14th April

### ISSUE THREAD

**Issue by brainasium** [sdavis3/code-coverage-widgets#41]
Hi there, we have been using your code coverage widget for some time now and it has been working great. However since Thursday this week, the code coverage page just comes back blank on all our projects that use it in Azure DevOps. 

![image](https://user-images.githubusercontent.com/48318350/115032006-bacf7680-9ec0-11eb-952f-a5c3df9bb98e.png)

Also getting this error 
![image](https://user-images.githubusercontent.com/48318350/115032094-d470be00-9ec0-11eb-967b-4fea80296b0d.png)

The tests are still running and publishing artefacts 
![image](https://user-images.githubusercontent.com/48318350/115032218-fcf8b800-9ec0-11eb-8492-34a44dc2c866.png)

**Comment by sdavis3** [comment]
The first image (Cover Coverage tab) is built in Azure DevOps functionality. If that's blank, then all code coverage metrics are broken across Azure DevOps. You are the first to report this, but I suspect there is an API issue internal to Azure DevOps that's unrelated to my widget. If the Code Coverage tab (not my widget) is supplying data, then my widget doesn't have a chance of working :) The only visual manifestation of my widget is on a dashboard.

**Comment by brainasium** [comment]
Hi, thanks for your speedy response. 

We are using the online version of Azure DevOps. 

Thanks, I've raised a ticket with Microsoft.

**Comment by sdavis3** [comment]
Were you able to get resolution to this issue?

**Comment by brainasium** [comment]
Yeah, Microsoft got back to me on Friday. Can close this issue as it looks like it is caused by the Publish Code coverage Results task. 

Microsoft Product Group has reproduced this issue in UK South Region and they suspect that the issue is caused by the Publish Code coverage Results task.

They are currently working on a resolution.
