### ISSUE TITLE
Do you support coverage cobertura xml file 

### ISSUE THREAD

**Issue by Eldadc** [sdavis3/code-coverage-widgets#42]
Hi,

Do you support coverage cobertura xml file ?

Thanks

**Comment by sdavis3** [comment]
This widget uses Azure DevOps information to render code coverage. So, if you are able to see your metrics in Azure DevOps, this widget should show those details in the widget correctly. In other words, it supports only what Azure DevOps supports.

**Comment by Eldadc** [comment]
Hi,

Do you mean if a code coverage tab have been created as azure devops-HTML ?

Thanks

**Comment by sdavis3** [comment]
Correct. This widget surfaces information already found elsewhere in Azure DevOps. So, if you are already seeing it in the Code Coverage tab, then this widget should work.
